Resources:
  DB:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 20
        BackupRetentionPeriod: 0 # default: 1
        CopyTagsToSnapshot: true # default: false
        DBInstanceClass: db.t2.micro
        DBInstanceIdentifier: machendradb
        DBName: 'machendradb'
        DBSubnetGroupName: 'machendra-rdssn'
        Engine: 'mysql'
        EngineVersion: '8.0.20'
        LicenseModel: 'general-public-license'
        MasterUsername: 'admin'
        MasterUserPassword: Machi$12345
        MaxAllocatedStorage: 22
        MultiAZ: true
        PubliclyAccessible: false
        StorageType: gp2
        VPCSecurityGroups:
          - sg-0dc7ddc59b3038d61
